#pragma config(UserModel, "Device Configuration.h")
//Code automatically generated by 'ROBOTC' configuration wizard
#include "turnDegrees.h"
#include "distance.h"
//Developed by Luke A. Simmons

task main(){
	//Example of turnDegrees
	turnDegrees(120, 50);

	//Example of "goToDistance"
	goToDistance(5, 50, "distance", "backward");
}
