#pragma config(UserModel, "Device Configuration.h")
//Code automatically generated by 'ROBOTC' configuration wizard!!
//Developed by Luke A. Simmons

void turnDegrees(int goHere, float speed){
	if(goHere < 0){
		goHere += 360;
	}
	int currentLoc = getGyroHeading(gyroSensor);
	int toGo = currentLoc - goHere;
	if((toGo <= 180 && toGo >=0) || (toGo < 0 && toGo <= -180)){
			repeatUntil(getGyroHeading(gyroSensor) == goHere || getGyroHeading(gyroSensor) == goHere - 360){
				setMotor(leftMotor, speed);
				setMotor(rightMotor, -speed);
			}
	}
	else if((toGo > 180 && toGo >= 0) || (toGo < 0 && toGo > -180)){
			repeatUntil(getGyroHeading(gyroSensor) == goHere || getGyroHeading(gyroSensor) == goHere - 360){
				setMotor(leftMotor, -speed);
				setMotor(rightMotor, speed);
			}
		}
	stopMultipleMotors(leftMotor, rightMotor);
}
